<?php
return array (
  'thread_field_choice.auction_Ends_At_Option_1' => 'Option 1',
  'thread_field_choice.auction_Ends_At_Option_2' => 'Option 2',
  'thread_field_choice.auction_guidelines_0' => 'These are the Auction Guidelines. Please read carefully.',
  'thread_field_choice.bid_increament_10' => '10',
  'thread_field_choice.bid_increament_5' => '5',
  'thread_field_choice.bumping_rules_0' => 'I have read and accept the auction bumping rules.',
  'thread_field_choice.payment_methods_First_Method' => 'First Method',
  'thread_field_choice.payment_methods_Second_Method' => 'Second Method',
  'thread_field_choice.shipping_term_shiping_term_1' => 'Term 1',
  'thread_field_choice.shipping_term_shiping_term_2' => 'Term 2',
  'thread_field_choice.ships_via_ships_1' => 'ships 1',
  'thread_field_choice.ships_via_ships_2' => 'ships 2',
  'thread_field_choice.testing_check_12' => 'gfdfdg',
  'thread_field_choice.testing_check_23' => 'rfetertert',
  'thread_field_choice.testing_check_45' => 'dfsgdsdf',
  'thread_field_choice.testing_check_56' => 'sdfwqesdf',
  'thread_field_choice.testing_multiple_2' => 'dsfdfsfd',
  'thread_field_choice.testing_multiple_23' => 'sdfsdfsdf',
  'thread_field_choice.testing_multiple_34' => 'sdfdsfsdgf',
  'thread_field_choice.testing_multiple_45' => 'sdfsdfsdf',
  'thread_field_choice.testing_multiple_67' => 'sdfsdfsdf',
  'thread_field_choice.testing_radio_12' => 'dfgdfgdfg',
  'thread_field_choice.testing_radio_234' => '34wsrwr',
  'thread_field_choice.testing_radio_324' => 'fdgdfgdfg',
  'thread_field_choice.testing_star_1' => 'werwe',
  'thread_field_choice.testing_star_2' => 'werwer',
  'thread_field_choice.testing_star_3' => 'werewrer',
  'thread_field_choice.testing_star_4' => 'erwtert',
  'thread_field_choice.testing_star_5' => 'ertert',
);