<?php
return array (
  'thread_field_title.asdsadsdasd' => 'asdsadsad',
  'thread_field_title.auction_Ends_At' => 'auction_time_zone',
  'thread_field_title.auction_guidelines' => 'AUCTION GUIDLINES',
  'thread_field_title.bid_increament' => 'MINIMUM BID INCREMENT',
  'thread_field_title.bumping_rules' => 'Auction Bumping Rules',
  'thread_field_title.gameTitle' => 'Game Title',
  'thread_field_title.model' => 'Model',
  'thread_field_title.multi_tags' => 'Multi Tags Field',
  'thread_field_title.payment_methods' => 'PAYMENTS ACCEPTED',
  'thread_field_title.price' => 'Price',
  'thread_field_title.shipping_term' => 'SHIPPING TERMS',
  'thread_field_title.ships_via' => 'SHIPS VIA',
  'thread_field_title.starting_bid' => 'starting_bid',
  'thread_field_title.testing_check' => 'Check boxes',
  'thread_field_title.testing_field_id' => 'Testing Thread Fiels',
  'thread_field_title.testing_multi' => 'Multi-line text box',
  'thread_field_title.testing_multiple' => 'Multiple-choice drop down',
  'thread_field_title.testing_radio' => 'Radio buttons',
  'thread_field_title.testing_rich' => 'Rich text box',
  'thread_field_title.testing_star' => 'Star rating',
  'thread_field_title.version' => 'Version',
);